<!DOCTYPE html>
<html lang="en">
<head>
  <title>STUDENT DATACARD</title>
  <link rel="icon" type="image/gif/png" href="smartcard.png">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <style>
	img{
	display: block;
  	margin-left: auto;
  	margin-right: auto;
	}	
  body{
    font-family: 'Open Sans', sans-serif;
  }
</style>
</head>
<body style="height:1500px">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
    <ul class="nav navbar-nav">
      <li><img class="img-responsive" src="student datacard icon.png" alt="Student Datacard" width="50" height="25"></li>
      <li>&nbsp;</li>
      <li><a class="navbar-brand" href="index.php">Student Datacard</a></li>
    </ul>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="index.php">Home</a></li>
        <!--<li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li>-->
        <li><a href="signup.php">Apply for Student Datacard</a></li>
        <li><a href="aboutus.php">About Us</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="signup.php"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="login.php"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="jumbotron text-center" style="margin-top: -28px;">
  <h1>Student Datacard - A Centralized Document Storage System</h1>
  <p>A centralized and secure storage of your documents accessible through our Customized Student Datacard</p> 
  <div class="container">
  <img class="img-responsive" src="student datacard.png" alt="Student Datacard" width="800" height="400"> 
</div>
</div>

<div class="jumbotron text-center" style="background-color: black;color: white;margin-top: -28px;">
<h2>INSIGHT OF THE PROJECT</h2><br/>
  <div class="row">
  <div class="col-sm-4 col-md-4 col-lg-4">
      <h3>DESCRIPTION OF STUDENT DATACARD</h3><br/>
      <img src="student datacard.png" class="img-responsive" width="380" height="250"><br/>
      <p>Technology is developing with growing concept of digital market. The concept of Document Storage Student Datacard takes a step more strongly toward the digitalization of world. Student Datacard is developed to reduce the burden of carrying any kind of important documents</p>
  </div>  
  <div class="col-sm-4 col-md-4 col-lg-4">
      <h3>CLOUD STORAGE</h3><br/>
      <img src="cloud.jpg" class="img-responsive" width="380" height="250"><br/>
      <p>The documents will be stored in logical pools of cloud storage.A Hybrid type of cloud storage will be utilized for the purpose.Benefits of using Cloud services it’s anytime anywhere accessibility, remote backup and so on. It helps to cut costs in maintaining the data backups and system overload.</p>
  </div>  
  <div class="col-sm-4 col-md-4 col-lg-4">
      <h3>2FA FOR SECURITY</h3><br/>
      <img src="2fa.jpg" class="img-responsive" width="380" height="250"><br/>
      <p>Two factor authentication (2FA) is a method of confirming a user's claimed identity by utilizing something they know (password) and a second factor other than something they have or something they are. and second factor being the user repeating back something that was sent to them or an OTP generated by an app that is common to the user and the authentication system.
      </p>
  </div>  
</div>
</div>

<!--footer-->

  <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
          <ul class="list-unstyled list-inline social text-center">
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-facebook fa-lg" ></i></a></li>
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-twitter fa-lg"></i></a></li>
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-instagram fa-lg"></i></a></li>
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-google-plus fa-lg"></i></a></li>
            <li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope fa-lg"></i></a></li>
          </ul>
        </div>
        </hr>
      </div>  
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
          <p style="font-size: 15px;"><u><a href="smartcard123.000webhostapp.com">Student Datacard Corporation</a></u> is a Registered MSP/ISO of Elavon, Inc. [a wholly owned subsidiary of India MN]</p>
          <p style="font-size: 15px;"class="h6">&copy All right Reversed.<a class="text-green ml-2" href="smartcard123.000webhostapp.com" target="_blank">StudentDatacard</a></p>
        </div>
        </hr>
      </div>  
    </div>

</body>
</html>